service: serverless-reminder-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.dbTableName}
    - Effect: Allow
      Action: 
        - SNS:Publish
        - SNS:SetSMSAttributes
        - SNS:ListSMSSandboxPhoneNumbers
        - SNS:CreateSMSSandboxPhoneNumber
        - SNS:VerifySmsSandboxPhoneNumber
      Resource:
        - "*"
    - Effect: Allow
      Action: 
        - ses:SendEmail
        - ses:ListIdentities
        - ses:VerifyEmailIdentity
      Resource:
        - arn:aws:ses:${self:provider.region}:${aws:accountId}:identity/*
    - Effect: Allow
      Action: 
        - ses:ListIdentities
        - ses:VerifyEmailIdentity
      Resource:
        - "*"            

custom:
  dbTableName: reminder-table
  fromEmail: 1999adithya@gmail.com

functions:
  verifyUser:
    handler: reminder/verifyUser.handler
    events:
      - http:
          path: /verify-user/add
          method: post

  addReminder:
    handler: reminder/addReminder.handler
    environment:
      ddbName: ${self:custom.dbTableName}
    events:
      - http:
          path: /reminder-app/add
          method: post

  sendReminder:
    handler: reminder/sendReminder.handler
    environment:
      fromEmail: ${self:custom.fromEmail}
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [reminderTable, StreamArn]
          filterPatterns:
            - eventName: [REMOVE]  

# you can add CloudFormation resource templates here
resources:
 Resources:
   reminderTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: ${self:custom.dbTableName}
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: ttl
            AttributeType: N  
        BillingMode: PROVISIONED
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: ttl
            KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification: 
            StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification: 
            AttributeName: ttl
            Enabled: True