service: serverless-remainder-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.dbTableName}

custom:
  dbTableName: remainder-table

functions:
  addRemainder:
    handler: remainder/addRemainder.handler
    environment:
      ddbName: ${self:custom.dbTableName}
    events:
      - http:
          path: /remainder-app/add
          method: post

  sendRemainder:
    handler: remainder/sendRemainder.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [remainderTable, StreamArn]
          filterPatterns:
            - eventName: [REMOVE]  

# you can add CloudFormation resource templates here
resources:
 Resources:
   remainderTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: ${self:custom.dbTableName}
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: ttl
            AttributeType: N  
        BillingMode: PROVISIONED
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: ttl
            KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification: 
            StreamViewType: NEW_IMAGE
        TimeToLiveSpecification: 
            AttributeName: ttl
            Enabled: True